### ISSUE TITLE
搭建没有报错，无法连接

### ISSUE THREAD

**Issue by xuconnery** [BoxXt/installReality#1]
root@instance-20230313-1136:/home/ubuntu# journalctl -u sing-box --output cat -f
+0000 2023-03-13 08:36:57 DEBUG dns: lookup succeed for objects.githubusercontent.com: 185.199.110.133 185.199.111.133 185.199.108.133 185.199.109.133
+0000 2023-03-13 08:36:57 INFO router: loaded geosite database: 1374 codes
+0000 2023-03-13 08:36:57 INFO inbound/vless[vless-in]: tcp server started at [::]:443
+0000 2023-03-13 08:36:57 INFO sing-box started (3.266s)
sing-box.service: Succeeded.
Started sing-box service.
+0000 2023-03-13 09:00:12 INFO router: loaded geoip database: 250 codes
+0000 2023-03-13 09:00:12 INFO router: loaded geosite database: 1374 codes
+0000 2023-03-13 09:00:12 INFO inbound/vless[vless-in]: tcp server started at [::]:443
+0000 2023-03-13 09:00:12 INFO sing-box started (0.11s)

**Comment by BoxXt** [comment]
用的什么客户端？配置是否正确给到meta客户端？

**Comment by xuconnery** [comment]
用的clashx meta mac ，是按照搭建过程给的配置保存的，而且我用Android的clash meta也是连接不上，不知道哪里出了问题

**Comment by BoxXt** [comment]
@xuconnery 就在一分钟前，我用脚本重新安装了一次，脚本给出的配置直接用clashx.META mac是可以使用的，脚本里面要求输入的私钥和公钥你有没有确定输入正确了？以下是我的软件测速截图
<img width="192" alt="image" src="https://user-images.githubusercontent.com/127529953/224675098-b1777cc8-6c4f-450a-a7c6-f2b6bc525296.png">

**Comment by BoxXt** [comment]
> 问题

你的客户端所使用的核心是否都是最新版本的内核？

**Comment by xuconnery** [comment]
私钥公钥都是复制粘贴的，应该没问题。我是新开的Oracle Ubuntu机子刚装的，客户端也都是刚下的最新版本，mac meta也使用了alpha内核

请问怎样完全卸载，我再重新安装一遍看看

**Comment by BoxXt** [comment]
> 私钥公钥都是复制粘贴的，应该没问题。我是新开的Oracle Ubuntu机子刚装的，客户端也都是刚下的最新版本，mac meta也使用了alpha内核
> 
> 请问怎样完全卸载，我再重新安装一遍看看

不需要卸载，重新执行脚本即可

**Comment by xuconnery** [comment]
[TCP] dial Proxy (match Match/) 172.19.0.1:44318 --> android.googleapis.com:443 error: 140.238.62.196:443 connect error: REALITY authentication failed

认证失败？私钥公钥都是复制粘贴，应该不会错啊。。。去哪里手动检查下呢

**Comment by xuconnery** [comment]
/usr/local/etc/sing-box/里的config.json检查了下，private_key没有错

**Comment by BoxXt** [comment]
> /usr/local/etc/sing-box/里的config.json检查了下，private_key没有错

你可以提供一个tg账号，我tg里面联系你调试下吧。

**Comment by xuconnery** [comment]
不折腾了😭
